server:
  port: ${PORT:8761}  #5000
security:
  user:
    password: ${eureka.password}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}
