server:
  port: ${PORT:8761}
security:
  user:
    password: ${eureka.password}

eureka:
  instance:
    hostname: ec2-54-163-225-208.compute-1.amazonaws.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}
